Reorder steps
install dependencies > install CMake > install Qt > build poppler >
build hunspell

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -186,14 +186,14 @@ jobs:
       with:
         update: true
 
+    - name: Install dependencies
+      # git is needed for getting git revision information
+      run: msys2do pacman --noconfirm -S git make mingw-w64-x86_64-qt5 mingw-w64-x86_64-gcc mingw-w64-x86_64-lua
+
     - name: Install CMake
       uses: ./.github/actions/install-cmake
       with:
         version: '${{ matrix.cmake }}'
-
-    - name: Install dependencies
-      # git is needed for getting git revision information
-      run: msys2do pacman --noconfirm -S git make mingw-w64-x86_64-qt5 mingw-w64-x86_64-gcc mingw-w64-x86_64-lua
 
 #    - name: Install Qt
 #      uses: jurplel/install-qt-action@v2
@@ -246,6 +246,11 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v2
 
+    - name: Install Dependencies
+      run: |
+        brew update > brew_update.log || { print_error "Updating homebrew failed"; cat brew_update.log; exit 1; }
+        brew install lua
+
     - name: Install CMake
       uses: ./.github/actions/install-cmake
       with:
@@ -267,13 +272,6 @@ jobs:
       uses: ./.github/actions/build-hunspell
       with:
         version: '${{ matrix.hunspell }}'
-
-    - name: Install Dependencies
-      run: |
-        brew update > brew_update.log || { print_error "Updating homebrew failed"; cat brew_update.log; exit 1; }
-        brew install lua
-
-    - run: echo "$Qt5_DIR"
 
     - name: Configure
       run: cmake -B build -DTW_BUILD_ID='github' ${GITHUB_WORKSPACE} -DCMAKE_PREFIX_PATH="/usr/local/opt/qt5"
